apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: cr.yandex/crp0irehbbj1n4pd0tf1/flask-app:v2
        ports:
          - containerPort: 8000
            name: "http-server"
        resources:
          requests:
            memory: 250Mi
            cpu: 300m
          limits:
            memory: 1Gi
            cpu: 600m
        env:
          - name: DATABASE_HOSTS
            value: postgres-service
          - name: DATABASE_URI
            value: postgresql://username:password@postgres-service:5432/hw_db?sslmode=disable